# Generated by Django 2.2.5 on 2019-09-15 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20190912_0743'),
        ('Home', '0008_auto_20190914_1150'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('std_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='dashboard.Student')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('mobile_no', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50, unique=True)),
                ('gender', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
    ]
