# Generated by Django 2.2.5 on 2019-09-15 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0010_attendance_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(max_length=50),
        ),
    ]
